### ISSUE TITLE
Provide requirements and instructions on how to run the pipeline

### ISSUE THREAD

**Issue by cyberbikepunk** [os-data/eu-structural-funds#126]
Other people need to be able to write and run the pipeline. So:
- [x] provide requirements.txt
- [x] provide instructions on running `dpp`
- [x] provide instruction on writing a pipeline

cc @pwalsh

**Comment by cyberbikepunk** [comment]
One issue is the relation of the `common` processors directory. 

Outside of PyCharm, this happens when I want to import a module from `plumbing`:

```
INFO:root:read_description: Traceback (most recent call last):
INFO:root:read_description:   File "/home/loic/repos/eu-structural-funds/common/read_description.py", line 15, in <module>
INFO:root:read_description:     from plumbing.config import DESCRIPTION_FILE, DATAPACKAGE_FILE
INFO:root:read_description: ImportError: No module named 'plumbing'
INFO:root:reshape_data: Traceback (most recent call last):
INFO:root:reshape_data:   File "/home/loic/repos/eu-structural-funds/common/reshape_data.py", line 6, in <module>
INFO:root:reshape_data:     from plumbing.utilities import get_fiscal_fields
INFO:root:reshape_data: ImportError: No module named 'plumbing'
```

**Comment by pwalsh** [comment]
you have some basic python packaging tasks to do: use of `__init__.py`, add the package to the python path, and so on. due to this repo being a diverse mix of code and data, how you go about this is open for debate. I'm still not sure when I read it how everything is imported at runtime, for example, custom code in a data directory.

**Comment by akariv** [comment]
processors are run in their own directory (so that they can use files without having to know anything about relative paths).
If you want to import stuff from a special place, then best thing is to add that to the PYTHONPATH. 
BTW, any reason not to have the plumbing code (or some of it, at least), under the common directory?

**Comment by cyberbikepunk** [comment]
Ideally i want to have all the code in one place to deal with imports correctly. I guess i could use the `common` directory for all python code and put the common processors in a folder called `processors`. That would be the easiest.

**Comment by akariv** [comment]
in that case yes, putting everything in one directory would be easiest.

**Comment by cyberbikepunk** [comment]
@pwalsh @akariv do I need python2 support? Since it's not a library, I was tempted to go for python3 only. Everything I've written so far is python3.
