### ISSUE TITLE
Multiple rows in CSVs (scraped by Michael)

### ISSUE THREAD

**Issue by michaeljokf** [os-data/eu-structural-funds#354]
Some of the PDFs I converted to CSVs, by using Tabula and then Open Refine, lead to some rows being multiplied. E.g. a project ist listed multiple times with exactly(!) the same information. This should not trouble the pipelines, but leads to faulty data.

Examples where I found this pattern so far: 
- ERDF Saarland 2007-2013
- ERDF Hessen 2007-2013

It might be prevalent in more files - I will have to check. 

Is this something that can (more or less) easily be solved by code? Or would it make more sense to rescrape the original PDF?

![image](https://cloud.githubusercontent.com/assets/22743376/21427029/7afa57bc-c852-11e6-908f-d3af8968d6a1.png)

**Comment by pwalsh** [comment]
@michaeljokf @akariv goodtables has a setting to detect duplicate rows. Well, the original version does. @roll can confirm if it is in the newest version.

**Comment by roll** [comment]
New version also supports this.

**Comment by michaeljokf** [comment]
well that is great! Thanks :) 
Does it also delete them / filter them out?

**Comment by pwalsh** [comment]
@michaeljokf no, but it tells you exactly where they occur.

**Comment by michaeljokf** [comment]
@pwalsh thank you! Yeah I think @ffalt is going to tackle this eventually.

**Comment by ffalt** [comment]
I filtered out the exact duplicates (lines and headers) and documented the removals into a .duplicate.csv e.g. [Saarland-ERDF-Data-2007-2013-1.duplicates.csv](https://github.com/os-data/eu-structural-funds/blob/master/data/DE.germany/DEC.saarland/ERDF%202007-2013/Saarland-ERDF-Data-2007-2013-1.duplicates.csv) and [Hessen-ERDF-2007_2013.duplicates.csv](https://github.com/os-data/eu-structural-funds/blob/master/data/DE.germany/DE7.hessen/ERDF%202007-2013/Hessen-ERDF-2007_2013.duplicates.csv)
I scanned all csv and found a lot of other files with duplicates. But before filtering any more, we need to decide if this is the way to handle it, since we need to recheck the original source and re-add any intentional duplicates which would be lost.

**Comment by michaeljokf** [comment]
@ffalt okay so I looked at the original files as discussed and made a list of which ones I found to be intentional duplicates, and which did not have any duplicates (and are due to scraping). Lets discuss how to tackle this exactly tomorrow. [List](https://docs.google.com/spreadsheets/d/1KYm2TVSpORTPmZ0d-jHUJcnZWF8MlbO9vijN-kO1tIg/edit#gid=0)
